# Generated by Django 5.0.1 on 2024-04-16 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_posts_timestamp_remove_posts_updated_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
